"""initial schema

Revision ID: 656eff2d798c
Revises: 
Create Date: 2025-09-18 14:03:24.376217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656eff2d798c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('caterers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caterers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caterers_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('daily_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caterer_id', sa.Integer(), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caterer_id', 'menu_date', name='uq_menu_per_caterer_per_date')
    )
    with op.batch_alter_table('daily_menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_menus_caterer_id'), ['caterer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_menus_cutoff_at'), ['cutoff_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_menus_menu_date'), ['menu_date'], unique=False)

    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_menu_id'], ['daily_menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dishes_daily_menu_id'), ['daily_menu_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caterer_id', sa.Integer(), nullable=False),
    sa.Column('daily_menu_id', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterers.id'], ),
    sa.ForeignKeyConstraint(['daily_menu_id'], ['daily_menus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_caterer_id'), ['caterer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_daily_menu_id'), ['daily_menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_dish_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_daily_menu_id'))
        batch_op.drop_index(batch_op.f('ix_orders_caterer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dishes_daily_menu_id'))

    op.drop_table('dishes')
    with op.batch_alter_table('daily_menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_menus_menu_date'))
        batch_op.drop_index(batch_op.f('ix_daily_menus_cutoff_at'))
        batch_op.drop_index(batch_op.f('ix_daily_menus_caterer_id'))

    op.drop_table('daily_menus')
    with op.batch_alter_table('caterers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caterers_owner_user_id'))

    op.drop_table('caterers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
